[package]
name = "gopro-telemetry"
version = "0.1.0"
authors = ["Richo Healey <richo@psych0tik.net>"]
edition = "2018"

[dependencies]
mp4parse = "0.11.2"
failure = "0.1.5"
log = "0.4.6"
nom = "4.2.2"

[dev-dependencies]
clap = "2.32.0"
pretty_env_logger = "0.3.0"
